In [1]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array

# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))

model.predict(data)

1/1 [==============================] - 3s 3s/step


array([[0.01070993]], dtype=float32)

In [2]:
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))

model.predict(data)

1/1 [==============================] - 2s 2s/step


array([[[0.01462537],
        [0.04112772],
        [0.07727934]]], dtype=float32)

In [3]:
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))

model.predict(data)

1/1 [==============================] - 0s 393ms/step


[array([[0.12968923]], dtype=float32),
 array([[0.12968923]], dtype=float32),
 array([[0.22650155]], dtype=float32)]

In [4]:
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_sequences=True ,return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))

model.predict(data)

1/1 [==============================] - 0s 373ms/step


[array([[[-0.02298517],
         [-0.05828331],
         [-0.09939912]]], dtype=float32),
 array([[-0.09939912]], dtype=float32),
 array([[-0.22189419]], dtype=float32)]